## docker-compose -p posrgres-approval -f docker-compose-approval.yml up -d

version: '3.9'

services:

  postgres-approval:
    image: postgres:14  # Specify a PostgreSQL version for consistency
    container_name: postgres-approval
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=roomdb  # Optional: Specify a default database
    volumes:
      - postgres_data_approval:/var/lib/postgresql/data
      - ./init/approval/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  pgadmin-approval:
    image: dpage/pgadmin4
    container_name: pgadmin-room
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_data_approval:/var/lib/pgadmin
    networks:
      - spring

volumes:
  postgres_data_approval:
  pgadmin_data_approval:

networks:
  spring:
    driver: bridge
