## docker-compose -p postgres-room -f docker-compose-room.yml up -d

version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-room
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/room:/var/lib/postgresql/data
      - ./init/room/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-room
    ports:
      - "8887:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - spring

networks:
  spring:
    driver: bridge

