#---------------------------------------------------------------------------------------------------------------------------
# 1. docker-compose -p mongodb-event -f docker-compose-event.yml up -d
#     - This command will start the containers in detached mode (-d) without rebuilding the image (if they exist)
#
# 2. docker-compose -p mongodb-event -f docker-compose-event.yml up -d --build
#       - this command forces the rebuild of image, even if they already exist, before starting them.
#
#-----------------------------------------------------------------------------------------------------------------------

version: '3.9'

services:

  mongo-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=event-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/event:/data/db  # Data persists here on the host machine
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Initialize MongoDB with a script
    container_name: mongodb_event
    networks:
      - spring

  mongo-express:
